In [1]:
import numpy as np
import pandas as pd

In [10]:
def linspacevsarange(n):
    # print(np.arange(n))
    # print(np.linspace(0,n,n))

    for i in range(1,n//2):
      a=np.arange(1,n,i)
      b=np.linspace(1,n,i)
      if len(a)==len(b):
        print("\n***********",i,len(a),a,b,"**********\n")
      else:
        print(i,a,b)


linspacevsarange(100)
# linspacevsarange(105) #bulamayacak

1 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99] [1.]
2 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99] [  1. 100.]
3 [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97] [  1.   50.5 100. ]
4 [ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97] [  1.  34.  67. 100.]
5 [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96] [  1.    25.75  50.5   75.25 100.  ]
6 [ 1  7 13 19 25 31 37 43 49 55 61 67 73 79 85 91 97] [  1.   20.8  40.6  60.4  80.2 100. ]
7 [ 1  8 15 22 29 36 43 50 57 64 71 78 85 92 99] [  1.   17.5  34.   50.5  67.   83.5 100. ]
8 [ 1  9 

In [11]:
arr=np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
arr[:,5].reshape(-1,1)

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [14]:
arr[:,[5]]

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [15]:
arr[:,5:6]

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [16]:
arr[2:4,2:5]

array([[22, 23, 24],
       [32, 33, 34]])

In [17]:
arr[2:4,2:5].T

array([[22, 32],
       [23, 33],
       [24, 34]])

In [20]:
arr[2:4,2:5].reshape(3,2)

array([[22, 23],
       [24, 32],
       [33, 34]])

In [48]:
df=pd.read_csv("https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/Di%C4%9Fer/movies.csv")
len(df)

27278

In [23]:
df.shape[0]

27278

In [24]:
# Title kolonundaki yıl bilgisini alıp başka kolona koyun, ve titledan da çıkarın. Son 5 kaydı gösterin. Bazılarında sonda fazladan boşluk olabilir
df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [33]:
df.iat[0,1]="Toy Story (95)"
df.head()

movieId                               title  \
0        1                      Toy Story (95)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [49]:
df["parantezlimi"]=df["title"].str.contains("\(")
df.query("parantezlimi==False")

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
/tmp/ipython-input-2526152118.py:1: SyntaxWarning: invalid escape sequence '\('
  df["parantezlimi"]=df["title"].str.contains("\(")


movieId                                  title                genres  \
10593    40697                              Babylon 5                Sci-Fi   
23617   112406  Brazil: In the Shadow of the Stadiums           Documentary   
23824   113190                     Slaying the Badger           Documentary   
24286   115133             Tatort: Im Schmerz geboren                 Crime   
24412   115685    National Theatre Live: Frankenstein         Drama|Fantasy   
26115   125571   The Court-Martial of Jackie Robinson    (no genres listed)   
26127   125632                          In Our Garden    (no genres listed)   
26180   125958     Stephen Fry In America - New World    (no genres listed)   
26335   126438         Two: The Story of Roman & Nyro     Documentary|Drama   
26395   126929                          Li'l Quinquin    (no genres listed)   
26432   127005        A Year Along the Abandoned Road    (no genres listed)   
26749   128612                             Body/Cialo  Comedy|Drama|Mystery   
26784   128734                          Polskie gówno        Comedy|Musical   
26963   129651       The Third Reich: The Rise & Fall    (no genres listed)   
26974   129705                             My Own Man    (no genres listed)   
27027   129887                            Moving Alan    (no genres listed)   
27114   130454    Michael Laudrup - en Fodboldspiller    (no genres listed)   

       parantezlimi  
10593         False  
23617         False  
23824         False  
24286         False  
24412         False  
26115         False  
26127         False  
26180         False  
26335         False  
26395         False  
26432         False  
26749         False  
26784         False  
26963         False  
26974         False  
27027         False  
27114         False

In [52]:
df["Yıl"]=df["title"].map(lambda x:x.split("(")[1][:-1] if "(" in x else np.nan)
df["#Genres1"]=df["genres"].map(lambda x:len(x.split("|")) if not "(" in x else 0)
df["#Genres2"]=df["genres"].map(lambda x:x.count("|")+1 if not "(" in x else 0)
df.query("parantezlimi==False").head()

movieId                                  title         genres  \
10593    40697                              Babylon 5         Sci-Fi   
23617   112406  Brazil: In the Shadow of the Stadiums    Documentary   
23824   113190                     Slaying the Badger    Documentary   
24286   115133             Tatort: Im Schmerz geboren          Crime   
24412   115685    National Theatre Live: Frankenstein  Drama|Fantasy   

       parantezlimi  Yıl  #Genres1  #Genres2  
10593         False  NaN         1         1  
23617         False  NaN         1         1  
23824         False  NaN         1         1  
24286         False  NaN         1         1  
24412         False  NaN         2         2

In [53]:
df.iloc[26115,:]

movieId                                       125571
title           The Court-Martial of Jackie Robinson
genres                            (no genres listed)
parantezlimi                                   False
Yıl                                              NaN
#Genres1                                           0
#Genres2                                           0
Name: 26115, dtype: object

In [34]:
df.head()["title"].str[-5:-1]

0     (95
1    1995
2    1995
3    1995
4    1995
Name: title, dtype: object

In [35]:
df.head()["title"].map(lambda x:x[-5:-1])

0     (95
1    1995
2    1995
3    1995
4    1995
Name: title, dtype: object

In [36]:
df.head()["title"].map(lambda x:x.split("(")[1][:-1])

0      95
1    1995
2    1995
3    1995
4    1995
Name: title, dtype: object