In [23]:
import pandas as pd
import numpy as np

In [24]:
dizi1D=np.array([1,2,3,4,5,6,])
dizi2D=np.array([[1,2,3,],[4,5,6]])

In [26]:
dizi1D.ndim, dizi2D.ndim

(1, 2)

In [28]:
dizi2D.shape

(2, 3)

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.diag((2,5,9))

array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [42]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
np.arange(20).reshape(2,-1) #r,c; r satıra, n/r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
np.arange(20).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [44]:
np.arange(20).reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [45]:
m45 = np.arange(20).reshape(4,-1)
m45

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
m45[0]

array([0, 1, 2, 3, 4])

In [49]:
m45[0:1]

array([[0, 1, 2, 3, 4]])

In [50]:
m45[[0]]

array([[0, 1, 2, 3, 4]])

In [51]:
m45[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
m45[1:3,1:4].T

array([[ 6, 11],
       [ 7, 12],
       [ 8, 13]])

In [56]:
m45[1:3,1:4].reshape(3,-1)

array([[ 6,  7],
       [ 8, 11],
       [12, 13]])

In [57]:
m45[...,1]

array([ 1,  6, 11, 16])

In [60]:
m45[:,1]

array([ 1,  6, 11, 16])

In [59]:
m45[::,1]

array([ 1,  6, 11, 16])

In [61]:
arr=np.array([1,2,np.nan,4])
print(arr.sum()) #nan

nan


In [62]:
np.nansum(arr)

np.float64(7.0)

In [63]:
dizi=np.array([1,1,1,2,3,4,4,4,5])
np.unique(dizi)

array([1, 2, 3, 4, 5])

In [64]:
unique_elements, counts = np.unique(dizi, return_counts=True)
frequency = dict(zip(unique_elements, counts))

print("Dizi elemanlarının frekansı:")
print(frequency)

Dizi elemanlarının frekansı:
{np.int64(1): np.int64(3), np.int64(2): np.int64(1), np.int64(3): np.int64(1), np.int64(4): np.int64(3), np.int64(5): np.int64(1)}


In [73]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]]) #,[9,10]
a1

array([[1, 2],
       [3, 4]])

In [74]:
a2

array([[5, 6],
       [7, 8]])

In [75]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [76]:
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [77]:
np.concatenate((a1,a2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [78]:
np.concatenate((a1,a2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Pandas

In [79]:
np.array([1,2,3])

array([1, 2, 3])

In [83]:
import pandas as pd
s1 = pd.Series({'a':1,'b':2})
s1

a    1
b    2
dtype: int64

In [81]:
pd.Series(5,index=[0,1,2,3])

0    5
1    5
2    5
3    5
dtype: int64

In [84]:
s1["a"]

np.int64(1)

In [85]:
s1.shape, type(s1)

((2,), pandas.core.series.Series)

Boyutlarda

- (2,) : bir boyutlu bir yapıdır, 2 satır 1 kolon
- (2,1): iki boyutlu bir yapıdır, 2 satır 1 kolon

In [87]:
listeden=pd.Series([1,2,3])
listeden.where(listeden>1,0)

0    0
1    2
2    3
dtype: int64

In [147]:
#dictten. Bunu, aşağıda çok kullanacağız
dict_={"Isimler":["ali","veli","can","murat","elif","ayben","serkan"],
      "Yaslar":[40,36,38,34,42,18,24],
       "Maaslar":[100,200,250,150,180,165,40],
       "Ucretler":[20,25,24,23,30,45,12],
       "Siciller":["35516","12345","45678","12458","78895","45231","45730"]
      }
df=pd.DataFrame(dict_)
df

Isimler  Yaslar  Maaslar  Ucretler Siciller
0     ali      40      100        20    35516
1    veli      36      200        25    12345
2     can      38      250        24    45678
3   murat      34      150        23    12458
4    elif      42      180        30    78895
5   ayben      18      165        45    45231
6  serkan      24       40        12    45730

In [121]:
path = 'https://raw.githubusercontent.com/VolkiTheDreamer/dataset/master/'

In [91]:
dcsv=pd.read_csv(path + "/Classification/iris.csv")
dcsv.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [92]:
df

Isimler  Yaslar  Maaslar  Ucretler Siciller
0     ali      40      100        20    35516
1    veli      36      200        25    12345
2     can      38      250        24    45678
3   murat      34      150        23    12458
4    elif      42      180        30    78895
5   ayben      18      165        45    45231
6  serkan      24       40        12    45730

In [93]:
df.info()
# object = strgin in pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Isimler   7 non-null      object
 1   Yaslar    7 non-null      int64 
 2   Maaslar   7 non-null      int64 
 3   Ucretler  7 non-null      int64 
 4   Siciller  7 non-null      object
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes


In [98]:
df.head(1)

Isimler  Yaslar  Maaslar  Ucretler Siciller
0     ali      40      100        20    35516

In [95]:
df.tail()

Isimler  Yaslar  Maaslar  Ucretler Siciller
2     can      38      250        24    45678
3   murat      34      150        23    12458
4    elif      42      180        30    78895
5   ayben      18      165        45    45231
6  serkan      24       40        12    45730

In [100]:
df.describe(include="all")

Isimler     Yaslar     Maaslar   Ucretler Siciller
count        7   7.000000    7.000000   7.000000        7
unique       7        NaN         NaN        NaN        7
top        ali        NaN         NaN        NaN    35516
freq         1        NaN         NaN        NaN        1
mean       NaN  33.142857  155.000000  25.571429      NaN
std        NaN   8.858679   68.373972  10.179344      NaN
min        NaN  18.000000   40.000000  12.000000      NaN
25%        NaN  29.000000  125.000000  21.500000      NaN
50%        NaN  36.000000  165.000000  24.000000      NaN
75%        NaN  39.000000  190.000000  27.500000      NaN
max        NaN  42.000000  250.000000  45.000000      NaN

In [148]:
df["Yeni1"]=pd.Series([10,20,30,40,50,60,70]) #bi seri ekleyerek
df["Yeni2"]=[-1,-2,-3,-4,-5,-6,-7] #liste ile
df["Yeni3"]=df["Maaslar"]+df["Ucretler"] #iki kolonu toplayarak
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3
0     ali      40      100        20    35516     10     -1    120
1    veli      36      200        25    12345     20     -2    225
2     can      38      250        24    45678     30     -3    274
3   murat      34      150        23    12458     40     -4    173
4    elif      42      180        30    78895     50     -5    210
5   ayben      18      165        45    45231     60     -6    210
6  serkan      24       40        12    45730     70     -7     52

In [123]:
df.Maaslar

0    100
1    200
2    250
3    150
4    180
5    165
6     40
Name: Maaslar, dtype: int64

In [124]:
df["Maaslar"]

0    100
1    200
2    250
3    150
4    180
5    165
6     40
Name: Maaslar, dtype: int64

In [149]:
#aggregate işlemler ile
ortmaas=df.Maaslar.mean()
df["Ort Maas"]=ortmaas
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas
0     ali      40      100        20    35516     10     -1    120     155.0
1    veli      36      200        25    12345     20     -2    225     155.0
2     can      38      250        24    45678     30     -3    274     155.0
3   murat      34      150        23    12458     40     -4    173     155.0
4    elif      42      180        30    78895     50     -5    210     155.0
5   ayben      18      165        45    45231     60     -6    210     155.0
6  serkan      24       40        12    45730     70     -7     52     155.0

In [150]:
#list comprehension ile
df["Maas_seviyesi"]=["düşük" if ortmaas>m else "yuksek" for m in df.Maaslar]
df["durum"]=["altta" if i<j else "ustunde" for (i,j) in zip(df.Maaslar,df["Ort Maas"])]
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516     10     -1    120     155.0   
1    veli      36      200        25    12345     20     -2    225     155.0   
2     can      38      250        24    45678     30     -3    274     155.0   
3   murat      34      150        23    12458     40     -4    173     155.0   
4    elif      42      180        30    78895     50     -5    210     155.0   
5   ayben      18      165        45    45231     60     -6    210     155.0   
6  serkan      24       40        12    45730     70     -7     52     155.0   

  Maas_seviyesi    durum  
0         düşük    altta  
1        yuksek  ustunde  
2        yuksek  ustunde  
3         düşük    altta  
4        yuksek  ustunde  
5        yuksek  ustunde  
6         düşük    altta

In [151]:
df.groupby("Maas_seviyesi")["Maaslar"].sum().rename("Seviye_Toplam")

Maas_seviyesi
düşük     290
yuksek    795
Name: Seviye_Toplam, dtype: int64

In [152]:
seviyetop = df.groupby("Maas_seviyesi")["Maaslar"].sum().rename("Seviye_Toplam").reset_index()
seviyetop

Maas_seviyesi  Seviye_Toplam
0         düşük            290
1        yuksek            795

In [153]:
df=df.merge(seviyetop)
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516     10     -1    120     155.0   
1    veli      36      200        25    12345     20     -2    225     155.0   
2     can      38      250        24    45678     30     -3    274     155.0   
3   murat      34      150        23    12458     40     -4    173     155.0   
4    elif      42      180        30    78895     50     -5    210     155.0   
5   ayben      18      165        45    45231     60     -6    210     155.0   
6  serkan      24       40        12    45730     70     -7     52     155.0   

  Maas_seviyesi    durum  Seviye_Toplam  
0         düşük    altta            290  
1        yuksek  ustunde            795  
2        yuksek  ustunde            795  
3         düşük    altta            290  
4        yuksek  ustunde            795  
5        yuksek  ustunde            795  
6         düşük    altta            290

In [155]:
#apply, map ve transform gibi metodlar ile
df["maasGrup"]=df.groupby("Maas_seviyesi")["Maaslar"].transform('sum')
df["Oran"]=df["Maaslar"]/df["maasGrup"]
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516     10     -1    120     155.0   
1    veli      36      200        25    12345     20     -2    225     155.0   
2     can      38      250        24    45678     30     -3    274     155.0   
3   murat      34      150        23    12458     40     -4    173     155.0   
4    elif      42      180        30    78895     50     -5    210     155.0   
5   ayben      18      165        45    45231     60     -6    210     155.0   
6  serkan      24       40        12    45730     70     -7     52     155.0   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
0         düşük    altta            290       290  0.344828  
1        yuksek  ustunde            795       795  0.251572  
2        yuksek  ustunde            795       795  0.314465  
3         düşük    altta            290       290  0.517241  
4        yuksek  ustunde            795       795  0.226415  
5        yuksek  ustunde            795       795  0.207547  
6         düşük    altta            290       290  0.137931

In [156]:
df["test"]=df.apply(lambda x: x.Yaslar*x.Maaslar,axis=1) #axis=1 dikkat
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516     10     -1    120     155.0   
1    veli      36      200        25    12345     20     -2    225     155.0   
2     can      38      250        24    45678     30     -3    274     155.0   
3   murat      34      150        23    12458     40     -4    173     155.0   
4    elif      42      180        30    78895     50     -5    210     155.0   
5   ayben      18      165        45    45231     60     -6    210     155.0   
6  serkan      24       40        12    45730     70     -7     52     155.0   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  test  
0         düşük    altta            290       290  0.344828  4000  
1        yuksek  ustunde            795       795  0.251572  7200  
2        yuksek  ustunde            795       795  0.314465  9500  
3         düşük    altta            290       290  0.517241  5100  
4        yuksek  ustunde            795       795  0.226415  7560  
5        yuksek  ustunde            795       795  0.207547  2970  
6         düşük    altta            290       290  0.137931   960

In [157]:
df.drop("test",inplace=False,axis=1) #son kolonu silelim

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516     10     -1    120     155.0   
1    veli      36      200        25    12345     20     -2    225     155.0   
2     can      38      250        24    45678     30     -3    274     155.0   
3   murat      34      150        23    12458     40     -4    173     155.0   
4    elif      42      180        30    78895     50     -5    210     155.0   
5   ayben      18      165        45    45231     60     -6    210     155.0   
6  serkan      24       40        12    45730     70     -7     52     155.0   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
0         düşük    altta            290       290  0.344828  
1        yuksek  ustunde            795       795  0.251572  
2        yuksek  ustunde            795       795  0.314465  
3         düşük    altta            290       290  0.517241  
4        yuksek  ustunde            795       795  0.226415  
5        yuksek  ustunde            795       795  0.207547  
6         düşük    altta            290       290  0.137931

In [158]:
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516     10     -1    120     155.0   
1    veli      36      200        25    12345     20     -2    225     155.0   
2     can      38      250        24    45678     30     -3    274     155.0   
3   murat      34      150        23    12458     40     -4    173     155.0   
4    elif      42      180        30    78895     50     -5    210     155.0   
5   ayben      18      165        45    45231     60     -6    210     155.0   
6  serkan      24       40        12    45730     70     -7     52     155.0   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  test  
0         düşük    altta            290       290  0.344828  4000  
1        yuksek  ustunde            795       795  0.251572  7200  
2        yuksek  ustunde            795       795  0.314465  9500  
3         düşük    altta            290       290  0.517241  5100  
4        yuksek  ustunde            795       795  0.226415  7560  
5        yuksek  ustunde            795       795  0.207547  2970  
6         düşük    altta            290       290  0.137931   960

In [159]:
del df["test"]

In [160]:
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516     10     -1    120     155.0   
1    veli      36      200        25    12345     20     -2    225     155.0   
2     can      38      250        24    45678     30     -3    274     155.0   
3   murat      34      150        23    12458     40     -4    173     155.0   
4    elif      42      180        30    78895     50     -5    210     155.0   
5   ayben      18      165        45    45231     60     -6    210     155.0   
6  serkan      24       40        12    45730     70     -7     52     155.0   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
0         düşük    altta            290       290  0.344828  
1        yuksek  ustunde            795       795  0.251572  
2        yuksek  ustunde            795       795  0.314465  
3         düşük    altta            290       290  0.517241  
4        yuksek  ustunde            795       795  0.226415  
5        yuksek  ustunde            795       795  0.207547  
6         düşük    altta            290       290  0.137931

In [162]:
np.nan, pd.NA, None

(nan, <NA>, None)

In [163]:
na=np.nan
liste=[["test",18,150,25,"34444",na,na,na,na,na,na,na,na,na]] #kolon sayısı kadar bilgi olmalı,olmayan bilgiler nan yapılır
temp_=pd.DataFrame(liste,columns=df.columns)
df=pd.concat([df,temp_], ignore_index=True) #kendisine atamayı unutma, son parametre de önemli, vermezsek indeks=0 olur
df

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0     ali      40      100        20    35516   10.0   -1.0  120.0     155.0   
1    veli      36      200        25    12345   20.0   -2.0  225.0     155.0   
2     can      38      250        24    45678   30.0   -3.0  274.0     155.0   
3   murat      34      150        23    12458   40.0   -4.0  173.0     155.0   
4    elif      42      180        30    78895   50.0   -5.0  210.0     155.0   
5   ayben      18      165        45    45231   60.0   -6.0  210.0     155.0   
6  serkan      24       40        12    45730   70.0   -7.0   52.0     155.0   
7    test      18      150        25    34444    NaN    NaN    NaN       NaN   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
0         düşük    altta          290.0     290.0  0.344828  
1        yuksek  ustunde          795.0     795.0  0.251572  
2        yuksek  ustunde          795.0     795.0  0.314465  
3         düşük    altta          290.0     290.0  0.517241  
4        yuksek  ustunde          795.0     795.0  0.226415  
5        yuksek  ustunde          795.0     795.0  0.207547  
6         düşük    altta          290.0     290.0  0.137931  
7           NaN      NaN            NaN       NaN       NaN

In [164]:
temp_

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
0    test      18      150        25    34444    NaN    NaN    NaN       NaN   

   Maas_seviyesi  durum  Seviye_Toplam  maasGrup  Oran  
0            NaN    NaN            NaN       NaN   NaN

In [167]:
df.isna().any().sum()

np.int64(9)

In [169]:
df[df["Maaslar"]>100]

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
1    veli      36      200        25    12345   20.0   -2.0  225.0     155.0   
2     can      38      250        24    45678   30.0   -3.0  274.0     155.0   
3   murat      34      150        23    12458   40.0   -4.0  173.0     155.0   
4    elif      42      180        30    78895   50.0   -5.0  210.0     155.0   
5   ayben      18      165        45    45231   60.0   -6.0  210.0     155.0   
7    test      18      150        25    34444    NaN    NaN    NaN       NaN   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
1        yuksek  ustunde          795.0     795.0  0.251572  
2        yuksek  ustunde          795.0     795.0  0.314465  
3         düşük    altta          290.0     290.0  0.517241  
4        yuksek  ustunde          795.0     795.0  0.226415  
5        yuksek  ustunde          795.0     795.0  0.207547  
7           NaN      NaN            NaN       NaN       NaN

In [170]:
df.query("Maaslar>100")

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
1    veli      36      200        25    12345   20.0   -2.0  225.0     155.0   
2     can      38      250        24    45678   30.0   -3.0  274.0     155.0   
3   murat      34      150        23    12458   40.0   -4.0  173.0     155.0   
4    elif      42      180        30    78895   50.0   -5.0  210.0     155.0   
5   ayben      18      165        45    45231   60.0   -6.0  210.0     155.0   
7    test      18      150        25    34444    NaN    NaN    NaN       NaN   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
1        yuksek  ustunde          795.0     795.0  0.251572  
2        yuksek  ustunde          795.0     795.0  0.314465  
3         düşük    altta          290.0     290.0  0.517241  
4        yuksek  ustunde          795.0     795.0  0.226415  
5        yuksek  ustunde          795.0     795.0  0.207547  
7           NaN      NaN            NaN       NaN       NaN

In [171]:
df.query("Maaslar>100 and Ucretler<40")

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
1    veli      36      200        25    12345   20.0   -2.0  225.0     155.0   
2     can      38      250        24    45678   30.0   -3.0  274.0     155.0   
3   murat      34      150        23    12458   40.0   -4.0  173.0     155.0   
4    elif      42      180        30    78895   50.0   -5.0  210.0     155.0   
7    test      18      150        25    34444    NaN    NaN    NaN       NaN   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
1        yuksek  ustunde          795.0     795.0  0.251572  
2        yuksek  ustunde          795.0     795.0  0.314465  
3         düşük    altta          290.0     290.0  0.517241  
4        yuksek  ustunde          795.0     795.0  0.226415  
7           NaN      NaN            NaN       NaN       NaN

In [173]:
kosul1=df["Maaslar"]>100
kosul2=df["Ucretler"]<40
df[np.logical_and(kosul1,kosul2)]

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
1    veli      36      200        25    12345   20.0   -2.0  225.0     155.0   
2     can      38      250        24    45678   30.0   -3.0  274.0     155.0   
3   murat      34      150        23    12458   40.0   -4.0  173.0     155.0   
4    elif      42      180        30    78895   50.0   -5.0  210.0     155.0   
7    test      18      150        25    34444    NaN    NaN    NaN       NaN   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
1        yuksek  ustunde          795.0     795.0  0.251572  
2        yuksek  ustunde          795.0     795.0  0.314465  
3         düşük    altta          290.0     290.0  0.517241  
4        yuksek  ustunde          795.0     795.0  0.226415  
7           NaN      NaN            NaN       NaN       NaN

In [176]:
df.iloc[2:4,:4]

Isimler  Yaslar  Maaslar  Ucretler
2     can      38      250        24
3   murat      34      150        23

In [174]:
df.iloc[2:4,:]

Isimler  Yaslar  Maaslar  Ucretler Siciller  Yeni1  Yeni2  Yeni3  Ort Maas  \
2     can      38      250        24    45678   30.0   -3.0  274.0     155.0   
3   murat      34      150        23    12458   40.0   -4.0  173.0     155.0   

  Maas_seviyesi    durum  Seviye_Toplam  maasGrup      Oran  
2        yuksek  ustunde          795.0     795.0  0.314465  
3         düşük    altta          290.0     290.0  0.517241

In [177]:
df.loc[2:4,["Isimler","Yaslar"]]

Isimler  Yaslar
2     can      38
3   murat      34
4    elif      42

In [178]:
df.Yaslar.values

array([40, 36, 38, 34, 42, 18, 24, 18])

In [179]:
df.Maas_seviyesi.value_counts()

Maas_seviyesi
yuksek    4
düşük     3
Name: count, dtype: int64

In [180]:
df.Maas_seviyesi.unique()

array(['düşük', 'yuksek', nan], dtype=object)

In [181]:
df.Maas_seviyesi.nunique()

2

In [182]:
df.nunique()

Isimler          8
Yaslar           7
Maaslar          7
Ucretler         7
Siciller         8
Yeni1            7
Yeni2            7
Yeni3            6
Ort Maas         1
Maas_seviyesi    2
durum            2
Seviye_Toplam    2
maasGrup         2
Oran             7
dtype: int64

In [ ]:
df.drop_duplicates

In [183]:
#sqlde
# select count(distinct A),count(distinct B),